name: PullRequest-Formatting

on:
  pull_request:
    branches: [main]

jobs:
  black-flake8:
    name: "pre-commit hooks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 black
      - name: github.ref # Debuging
        run: |
          echo "github.ref: ${{ github.ref }}"
      - uses: pre-commit/action@v2.0.0
