name: Main-PyPI-Test

on:
  push:
    branches: [main]

jobs:
  publish-test-pypi:
    name: Build and publish to Test PyPI
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install build tools
        run: >-
          python -m
          pip install
          build

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .

      - name: github.ref
        run: |
          echo "github.ref: ${{ github.ref }}"

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
